#!/bin/sh
# Install the `apm` command for this checkout.
#
# Checks the prerequisites, installs dependencies, builds every workspace
# package (daemon + web UI) and drops a small launcher into a directory on your
# PATH. Idempotent: re-run it after `git pull` to update.
#
# The launcher is a wrapper script, not a symlink into dist/, because `tsc`
# recreates dist files without the execute bit on every rebuild — the wrapper
# keeps its own.
#
#   sh scripts/install-cli.sh [--bin-dir DIR] [--launcher-only] [--uninstall]
set -eu

REPO_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
ENTRY_REL=packages/daemon/dist/main.js
BIN_DIR=${APM_BIN_DIR:-$HOME/.local/bin}
NODE_MIN=24
MODE=full

say() { printf 'apm-install: %s\n' "$1"; }
warn() { printf 'apm-install: warning: %s\n' "$1" >&2; }
die() {
  printf 'apm-install: error: %s\n' "$1" >&2
  exit 1
}

usage() {
  cat <<'EOF'
usage: sh scripts/install-cli.sh [options]

  --bin-dir DIR     where to install the launcher (default: ~/.local/bin,
                    or $APM_BIN_DIR)
  --launcher-only   only (re)write the launcher, skip install and build
  --uninstall       remove a launcher installed by this script
  -h, --help        show this help
EOF
}

while [ $# -gt 0 ]; do
  case $1 in
    --bin-dir)
      shift
      [ $# -gt 0 ] || die '--bin-dir needs a directory'
      BIN_DIR=$1
      ;;
    --bin-dir=*) BIN_DIR=${1#--bin-dir=} ;;
    --launcher-only) MODE=launcher-only ;;
    --uninstall) MODE=uninstall ;;
    -h | --help)
      usage
      exit 0
      ;;
    *) die "unknown option: $1 (try --help)" ;;
  esac
  shift
done

[ -n "$BIN_DIR" ] || die '--bin-dir must not be empty'
LAUNCHER=$BIN_DIR/apm
MARKER='ai-profile-manager launcher'

# ------------------------------------------------------------------ uninstall

if [ "$MODE" = uninstall ]; then
  if [ ! -e "$LAUNCHER" ]; then
    say "nothing to remove: $LAUNCHER does not exist"
  elif grep -q "$MARKER" "$LAUNCHER" 2>/dev/null; then
    rm -f "$LAUNCHER"
    say "removed $LAUNCHER"
  else
    die "$LAUNCHER was not installed by this script — remove it yourself if you meant to"
  fi
  say "your data in ${APM_DATA_DIR:-$HOME/.local/share/apm} was left alone; delete that directory to drop profiles and usage history"
  exit 0
fi

# --------------------------------------------------------------- prerequisites

command -v node >/dev/null 2>&1 ||
  die "node >= $NODE_MIN is not on your PATH — install it (e.g. \`mise install\` in this checkout, or from nodejs.org)"
NODE_BIN=$(command -v node)
NODE_VERSION=$("$NODE_BIN" --version 2>/dev/null) || die "\`$NODE_BIN --version\` failed — is that a working node?"
NODE_MAJOR=${NODE_VERSION#v}
NODE_MAJOR=${NODE_MAJOR%%.*}
case $NODE_MAJOR in
  '' | *[!0-9]*) die "cannot read a version number out of \`node --version\` ($NODE_VERSION)" ;;
esac
[ "$NODE_MAJOR" -ge "$NODE_MIN" ] ||
  die "node $NODE_VERSION is too old — apm needs node >= $NODE_MIN (e.g. \`mise install\` in this checkout)"

if [ "$MODE" = full ]; then
  command -v pnpm >/dev/null 2>&1 ||
    die "pnpm 11 is not on your PATH — \`npm i -g pnpm@11.3.0\`, or \`mise install\` in this checkout"
  if ! PNPM_VERSION=$(pnpm --version 2>&1); then
    die "\`pnpm --version\` failed:
$PNPM_VERSION

If pnpm comes from Corepack, it has to be a recent one: Corepack 0.24.0 — the
version Debian/Ubuntu ship as node-corepack — cannot launch pnpm 11 on any node
version and fails with ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING. Either
\`npm i -g corepack@latest\`, or install pnpm directly (\`npm i -g pnpm@11.3.0\`
or \`mise install\`) and keep the distro shim off your PATH."
  fi
  case $PNPM_VERSION in
    11.*) ;;
    *) warn "pnpm $PNPM_VERSION found, but this repo pins pnpm 11 (packageManager: pnpm@11.3.0)" ;;
  esac
fi

# ------------------------------------------------------------- install + build

if [ "$MODE" = full ]; then
  say "node $NODE_VERSION, pnpm $PNPM_VERSION"
  say 'installing dependencies'
  (cd "$REPO_DIR" && pnpm install)
  say 'building workspace packages'
  (cd "$REPO_DIR" && pnpm build)
fi

[ -f "$REPO_DIR/$ENTRY_REL" ] ||
  die "$REPO_DIR/$ENTRY_REL is missing — run this script without --launcher-only to build it"

# ------------------------------------------------------------------- launcher

mkdir -p "$BIN_DIR" || die "cannot create $BIN_DIR"
TMP=$LAUNCHER.tmp.$$
trap 'rm -f "$TMP"' EXIT

cat >"$TMP" <<EOF
#!/bin/sh
# $MARKER — generated by scripts/install-cli.sh, do not edit.
# Re-run \`pnpm install:cli\` in the checkout below to update or move it.
APM_ENTRY="$REPO_DIR/$ENTRY_REL"
APM_NODE="$NODE_BIN"
EOF
cat >>"$TMP" <<'EOF'
[ -x "$APM_NODE" ] || APM_NODE=$(command -v node) || {
  echo "apm: node is not on your PATH" >&2
  exit 1
}
[ -f "$APM_ENTRY" ] || {
  echo "apm: $APM_ENTRY is missing — rebuild the checkout with: pnpm install:cli" >&2
  exit 1
}
exec "$APM_NODE" "$APM_ENTRY" "$@"
EOF

chmod 755 "$TMP"
mv -f "$TMP" "$LAUNCHER"
trap - EXIT
say "installed $LAUNCHER -> $REPO_DIR/$ENTRY_REL"

case ":$PATH:" in
  *":$BIN_DIR:"*) say 'run `apm` from anywhere to open the dashboard' ;;
  *) warn "$BIN_DIR is not on your PATH — add this to your shell profile:
    export PATH=\"$BIN_DIR:\$PATH\"" ;;
esac
